repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: pretty-format-json
        args: ["--autofix", "--indent", "4", "--no-sort-keys"]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
        args: ["--config=.flake8"]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.20
    hooks:
      - id: isort
        additional_dependencies:
          - toml
